# TODAS as áreas do jogo COM UPDATE 3.0.1, E SUAS DLC, com seus pokémons EXCLUSIVOS DO POKÉMON VIOLET
#  tirando os pokémons exclusivos do pokémon SCARLET.


violet_map = {
    'south_province': {
        "poco_path": ["Hoppip", "Fletchling", "Scatterbug", "Lechonk", "Tarountula", "Pawmi", "Magikarp", "Wingull", "Buizel", "Arrokuda"],
        "area_one": ["Hoppip", "Happiny", "Fletchling", "Scatterbug", "Lechonk", "Tarountula", "Pawmi", "Pachirisu", "Pichu", "Bonsly", "Bounsweet", "Skwovet", "Shroodle", "Igglybuff", "Ralts", "Fidough", "Psyduck",
                     "Magikarp", "Wooper", "Surskit", "Azurill", "Chewtle", "Buizel", "Arrokuda", "Wingull", "Sunkern", "Combee", "Spewpa", "Oricorio", "Gastly", "Drowzee"],
        'area_two': ["Mareep", "Hoppip", "Starly", "Happiny", "Fltchling", "Maschiff", "Pikachu", "Pichu", "Bonsly", "Bounsweet", "Skwovet", "Applin", "Shroodle", "Jigglypuff", "Igglybuff", "Fidough", "Gastly",
                     "Misdreavus", "Skiddo", "Rockruff", "Psyduck", "Magikarp", "Azurill", "Buizel", "Chewtle", "Arrokuda", "Tadbulb", "Makuhita", "Yungoos", "Nacli", "Sunkern", "Combee", "Flabébé", "Diglett",
                     "Eevee", "Kricketot", "Smoliv", "Gastly", "Drowzee", "Bronzor", "Tinkatink"],
        'area_three': ["Murkrow", "Dunsparce", "Gulpin", "Happiny", "Rookidee", "Nymble", "Pawmi", "Shuppet", "Oricorio", "Tandemaus", "Squawkabilly", "Growlithe", "Makuhita", "Spoink", "Shinx", "Skiddo",
                       "Yungoos", "Pawmi", "Nacli", "Charcadet", "Klawf", "Gastly", "Drowzee", "Bronzor", "Tinkatink"],
        'area_four': ["Murkrow", "Dunsparce", "Starly", "Staravia", "Pachirisu", "Riolu", "Deerling", "Fletchinder", "Toxel", "Lechonk", "Tarountula", "Pawmo", "Pawmi", "Maschiff", "Toedscool", "Pikachu", "Pineco",
                      "Komala", "Applin", "Charcadet", "Shroodle", "Gastly", "Misdreavus", "Phanpy", "Meditite", "Swablu", "Rufflet", "Skiddo", "Rockruff", "Mudbray", "Flittle", "Psyduck", "Scyther",
                      "Magikarp", "Marill", "Wooper", "Barboach", "Basculin", "Goomy", "Chewtle", "Hatenna", "Dreepy", "Tadbulb", "Shellder", "Gyarados", "Qwilfish", "Luvdisc", "Wattrel", "Finizen", "Houndour",
                      "Makuhita", "Yungoos", "Gumshoos", "Nacli", "Combee", "Petilil", "Spewpa", "Flabébé", "Floette", "Bronzor", "Tinkatink"],
        'area_five': ["Mankey", "Skiploom", "Hoppip", "Murkrow", "Dunsparce", "Stantler", "Shroomish", "Slakoth", "Vigoroth", "Zangoose", "Seviper", "Luxio", "Pachirisu", "Deerling", "Fletchinder",
                      "Litleo", "Rookidee", "Corvisquire", "Lechonk", "Oinkologne", "Tarountula", "Pawmo", "Pawmi", "Toedscool", "Gastly", "Misdreavus", "Swablu", "Bagon", "Axew",
                      "Rufflet", "Skiddo", "Rockruff", "Mudbray", "Charcadet", "Flittle", "Psyduck", "Wooper", "Croagunk", "Goomy", "Chewtle", "Drednaw", "Dreepy", "Tadbulb", "Flamigo", "Clodsire", "Magikarp",
                      "Marill", "Surskit", "Barboach", "Basculin", "Arrokuda", "Wattrel", "Finizen", "Makuhita", "Yungoos", "Gumshoos", "Nacli", "Slowpoke", "Shellder", "Shellos", "Crabrawler", "Sandygast",
                      "Pincurchin", "Wiglett", "Combee", "Spewpa", "Flabébé", "Floette", "Fomantis", "Bronzor", "Tinkatink"],
        'area_six': ["Murkrow", "Banette", "Gothita", "Sylveon", "Klefki", "Sinistea", "Dachsbun", "Bombirdier", "Chansey", "Flareon", "Flaaffy", "Mareep", "Misdreavus", "Donphan", "Meditite", "Medicham",
                     "Altaria", "Honchkrow", "Gallade", "Rufflet", "Gogoat", "Lycanroc", "Mudbray", "Skwovet", "Toxtricity", "Lokix", "Houndstone", "Flittle", "Espathra", "Scovillain", "Pawmi", "Psyduck", "Golduck",
                     "Magikarp", "Vaporeon", "Whiscash", "Mismagius", "Basculin", "Drednaw", "Dreepy", "Clodsire", "Wooper", "Dratini", "Floatzel", "Tynamo", "Eelektrik", "Barraskewda", "Bellibolt", "Flamigo",
                     "Shellder", "Cloyster", "Gyarados", "Qwilfish", "Clauncher", "Clawitzer", "Kilowattrel", "Finizen", "Hariyama", "Gumshoos", "Copperajah", "Lokix", "Nacli", "Dugtrio", "Umbreon",
                     "Dunsparce", "Sableye", "Shelgon", "Gabite", "Salandit", "Salazzle", "Glimmet", "Jumpluff", "Sunflora", "Vespiquen", "Combee", "Lilligant", "Vivillon", "Floette",
                     "Dolliv", "Hypno", "Bronzong", "Tinkatuff"],
        'inlet_grotto': ["Digglet", "Houndour", "Yungoos"],
    },
    'west_province': {
        'asado_desert': ["Murkrow", "Dunsparce", "Pawmo", "Pawmi", "Toedscool", "Phanpy", "Donphan", "Cacnea", "Hippopotas", "Sandile", "Rufflet", "Larvesta", "Silicobra", "Bramblin", "Capsakid",
                         "Rellor", "Flittle", "Orthworm", "Psyduck", "Marill", "Buizel", "Chewtle", "Drednaw", "Dreepy", "Tadbulb", "Makuhita", "Skiddo", "Yungoos", "Gumshoos", "Lokix", "Nacli", "Charcadet",
                         "Combee", "Flabébé", "Floette", "Gastly", "Bronzor", "Falinks", "Tinkatuff"],
        'area_one': ["Mankey", "Gastly", "Misdreavus", "Phanpy", "Numel", "Swablu", "Skiddo", "Rockruff", "Mudbray", "Nymble", "Pawmo", "Pawmi", "Charcadet", "Capsakid", "Flittle", "Bombirdier",
                     "Psyduck", "Magikarp", "Buizel", "Basculin", "Chewtle", "Arrokuda", "Tadbulb", "Shellder", "Gyarados", "Qwilfish", "Wingull", "Luvdisc", "Wattrel", "Finizen", "Makuhita", "Yungoos", "Gumshoos",
                     "Nacli", "Diglett", "Dunsparce", "Sableye", "Bagon", "Gible", "Salandit", "Crabrawler", "Wiglett", "Combee", "Happiny", "Petilil", "Flabébé", "Floette", "Bronzor", "Falinks",
                     "Tinkatink"],
        'area_two': ["Meowth", "Chansey", "Tauros", "Ditto", "Flaaffy", "Murkrow", "Girafarig", "Dunsparce", "Donphan", "Phanpy", "Staravia", "Deerling", "Oinkologne", "Pawmo", "Pawmi", "Maschiff",
                     "Toedscool", "Cyclizar", "Grimer", "Kirlia", "Rotom", "Tandemaus", "Varoom", "Psyduck", "Slowpoke", "Magikarp", "Marill", "Azumarill", "Buizel", "Floatzel", "Croagunk",
                     "Basculin", "Chewtle", "Drednaw", "Arrokuda", "Barraskewda", "Dreepy", "Tadbulb", "Flamigo", "Shellder", "Gyarados", "Qwilfish", "Wingull", "Clauncher", "Wattrel", "Kilowattrel", "Finizen",
                     "Makuhita", "Hariyama", "Skiddo", "Yungoos", "Gumshoos", "Lokix", "Nacli", "Charcadet", "Shellos", "Crabrawler", "Sandygast", "Pincurchin", "Wiglett", "Wugtrio", "Diglett", "Dugtrio",
                     "Sableye", "Meditite", "Bagon", "Gible", "Noibat", "Salandit", "Glimmet"],
        'area_three': ["Meowth", "Persian", "Chansey", "Scyther", "Ditto", "Jumpluff", "Hoppip", "Espeon", "Murkrow", "Dunsparce", "Shroomish", "Vigoroth", "Tropius", "Staravia", "Pachirisu", "Zorua", "Deerling",
                       "Sawsbuck", "Fletchinder", "Oinkologne", "Pawmo", "Pawmi", "Maschiff", "Mabosstiff", "Toedscool", "Lilligant", "Pikachu", "Primeape", "Jolteon", "Sudowoodo", "Pineco", "Breloom", "Honchkrow",
                       "Leafeon", "Foongus", "Komala", "Greedent", "Skwovet", "Applin", "Spidops", "Tarountula", "Charcadet", "Shroodle", "Jigglypuff", "Voltorb", "Electrode", "Eevee",
                       "Dedenne", "Tandemaus", "Dachsbun", "Fidough", "Bombirdier", "Psyduck", "Magikarp", "Azumarill", "Marill", "Misdreavus", "Barboach", "Whiscash", "Basculin", "Goomy", "Drednaw", "Chewtle",
                       "Hatenna", "Dreepy", "Flamigo", "Clodsire", "Wooper", "Golduck", "Vaporeon", "Floatzel", "Buizel", "Barraskewda", "Arrokuda", "Tadbulb", "Bellibolt", "Hariyama", "Makuhita", "Skiddo",
                       "Gogoat", "Gumshoos", "Yungoos", "Lokix", "Nacli", "Naclstack", "Hypno", "Bronzong", "Tinkatuff", "Greavard"],
        'sea': ["Shellder", "Cloyster", "Magikarp", "Gyarados", "Qwilfish", "Wingull", "Pelipper", "Luvdisc", "Buizel", "Floatzel", "Finneon", "Lumineon", "Tynamo", "Eelektrik", "Clauncher",
                "Clawitzer", "Bruxish", "Arrokuda", "Barraskewda", "Veluza", "Finizen", "Wattrel", "Kilowattrel", "Bombirdier"]
    },
    'east_province': {
        'area_one': ["Tauros", "Skiploom", "Hoppip", "Murkrow", "Dunsparce", "Gulpin", "Deerling", "Litleo", "Steenee", "Rookidee", "Corvisquire", "Lechonk", "Oinkologne", "Pawmo", "Pawmi", "Toedscool", "Pikachu",
                     "Venonat", "Pineco", "Teddiursa", "Bounsweet", "Komala", "Applin", "Spidops", "Tarountula", "Shroodle", "Charcadet", "Shuppet", "Oricorio", "Tandemaus", "Squawkabilly", "Gastly",
                     "Misdreavus", "Swablu", "Rufflet", "Skiddo", "Rockruff", "Mudbray", "Flittle", "Psyduck", "Slowpoke", "Magikarp", "Marill", "Buizel", "Basculin", "Chewtle", "Drednaw", "Arrokuda", "Dreepy",
                     "Tadbulb", "Shellder", "Gyarados", "Qwilfish", "Luvdisc", "Clauncher", "Mareanie", "Finizen", "Wattrel", "Makuhita", "Yungoos", "Gumshoos", "Nacli", "Shellos", "Crabrawler", "Sandygast",
                     "Pincurchin", "Wiglett"],
        'area_two': ["Magnemite", "Chansey", "Tauros", "Marill", "Skiploom", "Hoppip", "Murkrow", "Dunsparce", "Deerling", "Rookidee", "Corvisquire", "Oinkologne", "Cyclizar", "Pawmo", "Pawmi", "Wattrel",
                     "Toedscool", "Venonat", "Pineco", "Komala", "Applin", "Spidops", "Tarountula", "Shroodle", "Charcadet", "Grimer", "Kirlia", "Shuppet", "Rotom", "Tandemaus", "Squawkabilly",
                     "Psyduck", "Slowpoke", "Magikarp", "Buizel", "Basculin", "Chewtle", "Drednaw", "Arrokuda", "Dreepy", "Tadbulb", "Shellder", "Gyarados", "Qwilfish", "Luvdisc", "Clauncher", "Mareanie",
                     "Finizen", "Makuhita", "Skiddo", "Yungoos", "Gumshoos", "Lokix", "Nacli", "Crabrawler", "Sandygast", "Pincurchin", "Wiglett", "Gastly", "Bronzor", "Mimikyu", "Tinkatink", "Tinkatuff"],
        'area_three': ["Meowth", "Magnemite", "Murkrow", "Dunsparce", "Rookidee", "Corvisquire", "Pawmo", "Toedscool", "Voltorb", "Shuppet", "Gothita", "Sinistea", "Tandemaus", "Dachsbun",
                       "Squawkabilly", "Varoom", "Psyduck", "Magikarp", "Misdreavus", "Barboach", "Basculin", "Goomy", "Chewtle", "Drednaw", "Dreepy", "Flamigo", "Clodsire", "Buizel", "Floatzel", "Pawniard",
                       "Arrokuda", "Barraskewda", "Tadbulb", "Shellder", "Gyarados", "Qwilfish", "Luvdisc", "Clauncher", "Finizen", "Wattrel", "Diglett", "Dugtrio", "Umbreon", "Makuhita", "Hariyama",
                       "Sableye", "Bagon", "Gabite", "Yungoos", "Gumshoos", "Salandit", "Salazzle", "Rolycoly", "Charcadet", "Glimmet", "Growlithe", "Gastly", "Torkoal", "Rufflet", "Carkol", "Silicobra",
                       "Cufant", "Bramblin", "Orthworm"],
        'sea': ["Shellder", "Cloyster", "Magikarp", "Gyarados", "Qwilfish", "Luvdisc", "Buizel", "Floatzel", "Clauncher", "Mareanie", "Bruxish", "Arrokuda", "Barraskewda", "Finizen",
                "Wattrel", "Kilowattrel", "Crabrawler", "Pincurchin", "Wiglett", "Wugtrio", "Nacli", "Chansey", "Sunflora", "Combee", "Vivillon", "Flabébé", "Floette", "Dolliv"]
    },
    'north_province': {
        'glaseado_mountain': ["Magneton", "Magnemite", "Haunter", "Gastly", "Chansey", "Flareon", "Ampharos", "Mareep", "Misdreavus", "Sneasel", "Ursaring", "Teddiursa", "Vigoroth", "Grumpig", "Spoink", "Altaria", "Swablu",
                              "Snorunt", "Honchkrow", "Murkrow", "Gallade", "Deerling", "Sawsbuck", "Axew", "Fraxure", "Cubchoo", "Rufflet", "Pyroar", "Litleo", "Gogoat", "Lycanroc", "Mudbray",
                              "Mudsdale", "Greedent", "Skwovet", "Snom", "Lokix", "Pawmo", "Pawmi", "Scovillain", "Flittle", "Espathra", "Tinkatuff", "Greavard", "Houndstone", "Cetoddle", "Delibird", "Glalie", "Bronzong",
                              "Glaceon", "Froslass", "Beartic", "Bergmite", "Avalugg", "Frosmoth", "Frigibax", "Hariyama", "Makuhita", "Gumshoos", "Yungoos", "Copperajah", "Cufant", "Naclstack", "Nacli", "Revavroom",
                              "Varoom", "Hypno", "Mimikyu"],
        'casseroya_lake': ["Glalie", "Bronzong", "Glaceon", "Froslass", "Beartic", "Frosmoth", "Houndstone", "Greavard", "Cetitan", "Cetoddle", "Golduck", "Slowpoke", "Slowbro", "Scyther", "Gyarados", "Vaporeon",
                           "Dratini", "Dragonair", "Azumarill", "Marill", "Swalot", "Gulpin", "Altaria", "Swablu", "Tropius", "Staraptor", "Mismagius", "Misdreavus", "Toxicroak", "Croagunk",
                           "Sliggoo", "Goomy", "Bergmite", "Avalugg", "Drednaw", "Chewtle", "Drakloak", "Dreepy", "Flamigo", "Veluza", "Dondozo", "Tatsugiri", "Floatzel", "Buizel", "Bellibolt", "Tadbulb",
                           "Cloyster", "Clawitzer", "Kilowattrel", "Honchkrow", "Murkrow", "Gogoat", "Hawlucha", "Copperajah", "Cufant", "Lokix", "Naclstack", "Nacli", "Gastrodon",
                           "Shellos", "Palossand", "Sandygast", "Pincurchin", "Wugtrio", "Mabosstiff", "Maschiff"],
        'dalizapa_passage': ["Magneton", "Magnemite", "Haunter", "Gastly", "Chansey", "Flareon", "Misdreavus", "Sneasel", "Ursaring", "Teddiursa", "Vigoroth", "Grumpig", "Spoink", "Snorunt",
                             "Honchkrow", "Murkrow", "Gallade", "Deerling", "Sawsbuck", "Axew", "Cubchoo", "Rufflet", "Pyroar", "Litleo", "Gogoat", "Lycanroc", "Mudbray", "Mudsdale", "Greedent", "Skwovet", "Snom",
                             "Lokix", "Pawmo", "Pawmi", "Scovillain", "Flittle", "Espathra", "Greavard", "Cetoddle", "Hariyama", "Makuhita", "Gumshoos", "Yungoos", "Naclstack", "Nacli", "Dugtrio", "Umbreon",
                             "Dunsparce", "Sableye", "Bagon", "Gabite", "Gible", "Salandit", "Salazzle", "Glimmet", "Frigibax"],
        'socarrat_trail': ["Raichu", "Jolteon", "Sudowoodo", "Forretress", "Heracross", "Slaking", "Honchkrow", "Murkrow", "Leafeon", "Zoroark", "Sawsbuck", "Deerling", "Amoonguss", "Foongus",
                           "Lurantis", "Fomantis", "Spidops", "Tarountula", "Mabosstiff", "Maschiff", "Brambleghast", "Toedscool", "Toedscruel"],
        'sea': ["Shellder", "Cloyster", "Magikarp", "Gyarados", "Qwilfish", "Pelipper", "Floatzel", "Buizel", "Lumineon", "Finneon", "Alomomola", "Tynamo", "Eelektrik", "Clauncher",
                "Clawitzer", "Bergmite", "Avalugg", "Barraskewda", "Arrokuda", "Eiscue", "Finizen", "Kilowattrel"],
        'area_one': ["Wigglytuff", "Jigglypuff", "Haunter", "Gastly", "Chansey", "Flareon", "Ampharos", "Mareep", "Ursaring", "Teddiursa", "Grumpig", "Spoink", "Altaria", "Swablu",
                     "Honchkrow", "Murkrow", "Lucario", "Riolu", "Gallade", "Sawsbuck", "Deerling", "Fraxure", "Axew", "Rufflet", "Gogoat", "Hawlucha", "Lycanroc", "Mudsdale", "Mudbray", "Indeedee",
                     "Lokix", "Pawmo", "Pawmi", "Brambleghast", "Scovillain", "Espathra", "Tinkatuff", "Houndstone", "Greavard", "Glalie", "Bronzong", "Weavile", "Sneasel", "Glaceon", "Froslass", "Beartic",
                     "Cubchoo", "Frosmoth", "Cetitan", "Cetoddle", "Golduck", "Vaporeon", "Dratini", "Whiscash", "Barboach", "Mismagius", "Misdreavus", "Drakloak", "Dreepy", "Flamigo", "Clodsire", "Wooper",
                     "Floatzel", "Buizel", "Bellibolt", "Tadbulb", "Cloyster", "Gyarados", "Alomomola", "Clawitzer", "Eiscue", "Kilowattrel", "Primeape", "Noibat", "Noivern",
                     "Copperajah", "Cufant", "Naclstack", "Nacli", "Revavroom", "Varoom", "Dugtrio", "Umbreon", "Sableye", "Gabite", "Gible", "Salazzle", "Salandit", "Glimmet",
                     "Wugtrio", "Jumpluff", "Hoppip", "Sunflora", "Blissey", "Vespiquen", "Combee", "Vivillon", "Floette", "Lurantis", "Fomantis"],
        'area_two': ["Golduck", "Scyther", "Vaporeon", "Dratini", "Altaria", "Swablu", "Mismagius", "Misdreavus", "Drakloak", "Dreepy", "Arcanine", "Growlithe", "Houndoom", "Houndour", "Camerupt", "Numel",
                     "Grumpig", "Spoink", "Luxray", "Shinx", "Honchkrow", "Murkrow", "Lucario", "Riolu", "Bisharp", "Pawniard", "Gogoat", "Hawlucha", "Noibat", "Noivern", "Copperajah", "Cufant", "Lokix",
                     "Naclstack", "Nacli", "Dugtrio", "Umbreon", "Sableye", "Gabite", "Gible", "Salazzle", "Salandit", "Glimmet", "Chansey", "Jumpluff", "Hoppip", "Blissey", "Vespiquen",
                     "Combee", "Vivillon", "Floette", "Lurantis", "Fomantis", "Venomoth", "Heracross", "Ursaring", "Teddiursa", "Kricketune", "Kricketot", "Foongus", "Amoonguss", "Passimian",
                     "Falinks", "Spidops", "Tarountula", "Bronzong", "Houndstone"],
        'area_three': ["Chansey", "Jumpluff", "Hoppip", "Espeon", "Pawmo", "Pawmi", "Glalie", "Bronzong", "Glaceon", "Froslass", "Beartic", "Cubchoo", "Frosmoth", "Houndstone", "Greavard", "Cetitan", "Cetoddle",
                       "Golduck", "Vaporeon", "Floatzel", "Buizel", "Barraskewda", "Arrokuda", "Drakloak", "Dreepy", "Bellibolt", "Tadbulb", "Flamigo", "Cloyster", "Gyarados", "Alomomola",
                       "Clawitzer", "Eiscue", "Kilowattrel", "Hariyama", "Makuhita", "Honchkrow", "Murkrow", "Gogoat", "Hawlucha", "Copperajah", "Cufant", "Lokix", "Naclstack", "Nacli", "Dugtrio", "Umbreon",
                       "Sableye", "Gabite", "Gible", "Salazzle", "Salandit", "Glimmet", "Pincurchin", "Wugtrio", "Sunflora", "Blissey", "Vespiquen", "Combee", "Lilligant", "Petilil",
                       "Vivillon", "Floette", "Florges", "Flabébé", "Dedenne", "Lurantis"],
    },
    'great_crater': {
        'upper_field': ["Raichu", "Venomoth", "Chansey", "Jumpluff", "Espeon", "Girafarig", "Medicham", "Meditite", "Braviary", "Floette", "Corviknight", "Frosmoth", "Pawmo", "Pawmi", "Farigiraf",
                        "Iron Bundle", "Iron Hands", "Iron Moth", "Golduck", "Vaporeon", "Altaria", "Swablu", "Floatzel", "Buizel", "Drakloak", "Dreepy", "Flamigo", "Donphan", "Phanpy", "Honchkrow",
                        "Murkrow", "Talonflame", "Gogoat", "Hawlucha", "Lycanroc", "Copperajah", "Cufant", "Lokix", "Naclstack", "Nacli", "Garganacl", "Iron Thorns"],
        'lower_field': ["Raichu", "Venomoth", "Chansey", "Espeon", "Girafarig", "Braviary", "Volcarona", "Floette", "Corviknight", "Pawmo", "Pawmi", "Farigiraf", "Iron Bundle",
                        "Iron Hands", "Golduck", "Vaporeon", "Masquerain", "Altaria", "Swablu", "Floatzel", "Buizel", "Bisharp", "Pawniard", "Drakloak", "Dreepy", "Bellibolt", "Tadbulb", "Flamigo", "Donphan",
                        "Phanpy", "Camerupt", "Numel", "Honchkrow", "Murkrow", "Talonflame", "Gogoat", "Hawlucha", "Lycanroc", "Lokix", "Naclstack", "Nacli", "Garganacl", "Iron Thorns"],
        'small_cave': ["Chansey", "Espeon", "Pawmo", "Pawmi", "Dugtrio", "Umbreon", "Sneasel", "Sableye", "Gabite", "Gible", "Weavile", "Lycanroc", "Salazzle", "Salandit", "Glimmet",
                       "Iron Jugulis"],
        'station_num_3_cave': ["Chansey", "Espeon", "Pawmo", "Pawmi", "Golduck", "Vaporeon", "Floatzel", "Buizel", "Drakloak", "Dreepy", "Dugtrio", "Umbreon", "Sneasel", "Sableye", "Gabite", "Gible", "Weavile",
                               "Zweilous", "Lycanroc", "Glimmet", "Iron Jugulis"],
        'waterfall_cave': ["Chansey", "Espeon", "Pawmo", "Pawmi", "Dugtrio", "Umbreon", "Sneasel", "Sableye", "Gabite", "Gible", "Weavile", "Zweilous", "Lycanroc", "Glimmet", "Iron Jugulis"],
        'grassy_cave': ["Chansey", "Espeon", "Pawmo", "Pawmi", "Golduck", "Vaporeon", "Floatzel", "Buizel", "Drakloak", "Dreepy", "Dugtrio", "Umbreon", "Sneasel", "Sableye", "Gabite", "Gible", "Weavile",
                        "Zweilous", "Lycanroc", "Glimmet", "Iron Jugulis", "Iron Valiant", "Houndstone"],
        'depths': ["Dugtrio", "Dunsparce", "Gabite", "Gible", "Zweilous", "Drakloak", "Dreepy", "Garganacl", "Hypno", "Espathra", "Glimmora", "Glimmet", "Dudunsparce",
                   "Iron Treads", "Iron Bundle", "Iron Hands", "Iron Jugulis", "Iron Valiant"]
    },
    'indigo_disk': {
        'kitakami_road': ["Spinarak", "Yanma", "Wooper", "Poochyena", "Volbeat", "Illumise", "Sewaddle", "Cutiefly", "Corphish", "Poliwag", "Geodude", "Sentret", "Furret"],
        'apple_hills': ["Ekans", "Bellsprout", "Sentret", "Spinarak", "Pichu", "Poochyena", "Volbeat", "Illumise", "Starly", "Sewaddle", "Fomantis", "Applin", "Geodude", "Gastly"],
        'raveler_road': ["Vulpix", "Sentret", "Furret", "Hoothoot", "Spinarak", "Aipom", "Heracross", "Swinub", "Stantler", "Seedot", "Ralts", "Starly", "Kricketot", "Kricketune", "Pachirisu", "Petilil", "Noibat",
                         "Rockruff", "Fomantis", "Skwovet", "Toedscool", "Poliwag", "Magikarp", "Wooper", "Corphish", "Riolu", "Phantump", "Poltchageist", "Sandshrew", "Clefairy", "Cleffa", "Geodude"],
        'oni_mountain': ["Growlithe", "Pichu", "Bonsly", "Timburr", "Noibat", "Hatenna", "Morpeko", "Tandemaus", "Magikarp", "Arrokuda", "Clefairy", "Hoothoot", "Cleffa"],
        'oni_maw': ["Growlithe", "Pichu", "Bonsly", "Timburr", "Noibat", "Hatenna", "Morpeko", "Tandemaus", "Magikarp", "Arrokuda", "Clefairy", "Hoothoot", "Cleffa"],
        'crystal_pool': ["Yanma", "Arrokuda", "Glimmet", "Clefairy", "Koffing", "Cleffa", "Slugma", "Duskull", "Chimecho", "Chingling", "Bronzor", "Litwick", "Ekans", "Dunsparce", "Bronzong", "Gible", "Gabite",
                         "Carbink", "Noibat", "Salandit", "Dudunsparce", "Barboach", "Feebas"],
        'wistful_field': ["Pikachu", "Mankey", "Hoothoot", "Noctowl", "Aipom", "Mightyena", "Lombre", "Lotad", "Ralts", "Kirlia", "Munchlax", "Petilil", "Mienfoo", "Grubbin", "Charjabug", "Cutiefly", "Rockruff",
                          "Skwovet", "Morpeko", "Tandemaus", "Riolu", "Houndour", "Gible", "Pawniard", "Yanma", "Sewaddle", "Swadloon", "Leavanny", "Oricorio", "Ribombee", "Lycanroc", "Greedent", "Sudowoodo",
                          "Shinx", "Luxio", "Timburr", "Nosepass"],
        'mossfell_confluence': ["Ekans", "Arbok", "Growlithe", "Bellsprout", "Weepinbell", "Gastly", "Haunter", "Gengar", "Hoothoot", "Noctowl", "Spinarak", "Ariados", "Heracross", "Seedot", "Nuzleaf", "Surskit",
                                "Volbeat", "Illumise", "Starly", "Staravia", "Timburr", "Gurdurr", "Sewaddle", "Swadloon", "Leavanny", "Ducklett", "Noibat", "Cutiefly", "Ribombee", "Fomantis", "Toedscool",
                                "Poliwag", "Poliwhirl", "Magikarp", "Wooper", "Quagsire", "Masquerain", "Corphish", "Chewtle", "Nosepass", "Shinx", "Luxio", "Oricorio", "Lycanroc", "Mienfoo", "Munchlax",
                                "Tandemaus", "Pawniard", "Gible", "Morpeko", "Rockruff", "Skwovet", "Greedent", "Petilil", "Yanma", "Aipom", "Kirlia", "Ralts", "Lotad", "Lombre", "Mightyena", "Sudowoodo",
                                "Shinx", "Luxio", "Timburr", "Poltchageist"],
        'fellhorn_gorge': ["Hoothoot", "Noctowl", "Aipom", "Wooper", "Starly", "Staravia", "Staraptor", "Riolu", "Ducklett", "Vullaby", "Noibat", "Rockruff", "Lycanroc", "Cramorant", "Bombirdier", "Poliwhirl",
                           "Gyarados", "Quagsire", "Barboach", "Whiscash", "Corphish", "Crawdaunt", "Chewtle", "Drednaw", "Arrokuda", "Barraskewda", "Gligar"],
        'paradise_barrens': ["Gastly", "Sudowoodo", "Gligar", "Houndour", "Shinx", "Luxio", "Bonsly", "Timburr", "Vullaby", "Jangmo-o", "Morpeko", "Tandemaus", "Bombirdier", "Sandshrew", "Sandslash", "Geodude",
                             "Nosepass", "Spoink", "Mudbray", "Orthworm"],
        'kitakami_wilds': ["Hoothoot", "Noctowl", "Spinarak", "Ariados", "Greedent", "Wooper", "Quagsire", "Chewtle", "Drednaw"],
        'infernal_pass': ["Magikarp", "Lotad", "Vulpix", "Geodude", "Graveler", "Koffing", "Slugma", "Houndour", "Houndoom", "Spoink", "Duskull", "Chingling", "Bronzor", "Rockruff", "Mimikyu", "Gastly", "Dunsparce",
                          "Gible", "Gabite", "Haunter", "Sneasel"],
        'chiling_waterhead': ["Wooper", "Quagsire", "Dunsparce", "Sneasel", "Swinub", "Piloswine", "Snorunt", "Tynamo", "Mienfoo", "Goomy", "Dudunsparce", "Magikarp", "Gyarados", "Arrokuda", "Barraskewda"]
    },
    'blueberry_academy': {
        'savanna_biome': ["Chansey", "Smeargle", "Trapinch", "Vibrava", "Flygon", "Deerling", "Sawsbuck", "Litleo", "Pyroar", "Rowlet", "Venonat", "Venomoth", "Doduo", "Dodrio", "Exeggcute", "Rhyhorn", "Scyther",
                          "Magmar", "Girafarig", "Scizor", "Magby", "Rotom", "Blitzle", "Zebstrika", "Sandile", "Krokorok", "Krookodile", "Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Fennekin", "Rellor",
                          "Rabsca", "Farigiraf", "Sobble", "Totodile", "Tynamo", "Eelektrik", "Dewpider", "Bruxish", "Exeggutor", "Rhydon", "Blissey", "Happiny", "Doduo", "Dodrio", "Electabuzz", "Elekid"],
        'coastal_biome': ["Grimer Alolan Form", "Muk Alolan Form", "Exeggcute", "Exeggutor Alolan Form", "Chikorita", "Smeargle", "Slakoth", "Zangoose", "Seviper", "Deerling Summer Form", "Sawsbuck Summer Form",
                          "Pikipek", "Trumbeak", "Toucannon", "Bellossom", "Popplio", "Crabrawler", "Tentacool", "Tentacruel", "Luvdisc", "Finneon", "Lumineon", "Inkay", "Diglett Alolan Form",
                          "Slowpoke Galarian Form", "Vigoroth", "Slaking", "Espurr", "Meowstic Male", "Meowstic Female", "Comfey", "Grookey", "Torkoal", "Fletchling", "Fletchinder", "Talonflame",
                          "Dewpider", "Araquanid", "Horsea", "Seadra", "Alomomola", "Minior", "Oddish", "Gloom", "Vileplume", "Cottonee", "Whimsicott", "Froakie", "Oricorio", "Rotom", "Bulbasaur", "Numel",
                          "Camerupt"],
        'canyon_biome': ["Scyther", "Scizor", "Smeargle", "Tyrogue", "Tepig", "Scraggy", "Scrafty", "Deerling", "Sawsbuck", "Squirtle", "Horsea", "Seadra", "Chinchou", "Lanturn", "Alomomola", "Geodude", "Graveler",
                         "Rotom", "Kleavor", "Electabuzz", "Elekid", "Turtwig", "Drilbur", "Excadrill", "Golett", "Golurk", "Litten", "Minior", "Skarmory", "Treecko", "Swablu", "Altaria", "Cranidos", "Shieldon",
                         "Minccino", "Cinccino", "Axew", "Fraxure", "Hitmonlee", "Hitmontop", "Espurr", "Meowstic", "Fletchling", "Fletchinder", "Hitmonchan"],
        'polar_biome': ["Seel", "Dewgong", "Porygon", "Smeargle", "Piplup", "Oshawott", "Minccino", "Cinccino", "Solosis", "Duosion", "Reuniclus", "Cubchoo", "Beartic", "Milcery", "Horsea", "Seadra", "Lapras",
                        "Qwilfish", "Finneon", "Lumineon", "Rotom", "Sandshrew", "Vulpix", "Snubbull", "Granbull", "Beldum", "Metang", "Chimchar", "Snover", "Abomasnow", "Deerling", "Sawsbuck", "Golett", "Golurk",
                        "Crabrawler", "Crabominable", "Minior", "Scorbunny", "Duraludon", "Torchic", "Numel", "Camerupt", "Axew", "Fraxure", "Cyndaquil"],
        'chargestone_cavern': ["Magnemite", "Magneton", "Electabuzz", "Elekid", "Plusle", "Minun", "Rotom", "Drilbur", "Excadrill", "Joltik", "Chespin", "Minior", "Porygon", "Beldum", "Metang", "Galvantula",
                               "Tynamo", "Eelektrik", "Eelektross"],
    }
}
